### ISSUE TITLE
[help wanted] Better stdlib documentation

### ISSUE THREAD

**Issue by narimiran** [nim-lang/Nim#10330]
I've started working on improving the documentation of Nim standard library, but that is a big task for only one person, so now I'm  asking for community help for some relatively small modules, where one could improve the documentation in their free time in a reasonable amount of time.

We now have the improved documentation for four most-used modules (`strutils`, `sequtils`, `tables`, `math`; see some [before and after screenshots](https://imgur.com/a/7pRwzfr)), and this can now be used as a guide/suggestion for you what the improved documentation consists of.
Basically: a short introduction with an example how to use the module and links to similar modules or modules which can be used in combination with the documented module; examples (using `runnableExamples`) of usages of procs and templates, with links to similar the procs/templates.

This is not complicated (you can use these already done modules to see how to do something, if necessary) and even newcomers to Nim can work on this task — if you need any help, write a comment below or ping me on IRC/Gitter.

When you make some changes, you can build .html locally with `nim doc path/to/file` to check if everything is rendered as it should.

Here is a list of modules which are in need for some love, in decreasing order of priority (based on the number of projects using them), but whichever of these you improve it is one step closer to our goal.
(If you don't have much time, I've marked the smallest modules which shouldn't take too long)

- [x] streams - @jiro4989 fixed it in #11059
- [x] random - @Jjp137 fixed it in #10546
- [x] algorithm - @ThomasTJdev fixed it in #10372
- [x] osproc - @narimiran fixed it in #10708
- [x] typetraits - @narimiran fixed it in #10752
- [x] hashes - @narimiran fixed it in #10752
- [x] parseutils - @ThomasTJdev fixed it in #10349
- [x] strtabs - @narimiran fixed it in #10704
- [x] unicode - @narimiran fixed it in #10921
- [ ] asyncnet
- [x] parseopt - short, @Jjp137 fixed it in #10398
- [x] threadpool - @narimiran fixed it in #10752
- [x] logging - @Jjp137 fixed it in #10895
- [x] base64 - short, @ThomasTJdev fixed it in #10371 
- [x] uri - short, @ThomasTJdev fixed it in #10373 
- [ ] asynchttpserver - short
- [ ] locks - short
- [x] md5 - @narimiran fixed it in #10752
- [x] db_sqlite - @jiro4989 fixed it in #11266
- [x] colors - @narimiran fixed it in #11295
- [x] marshal - @narimiran fixed it in #11398
- [x] sha1 - short, @ThomasTJdev fixed it in #10374 
- [x] parsecsv - @jiro4989 fixed it in #10391
- [ ] jsffi - @alehander42 is working on it

If some module is not on this list, that means it either already has an okayish documentation (to be improved later) or I plan to work on it (EDIT: or it is not used very often, based on [this](https://gist.github.com/GULPF/dc97e5e745842138556d882c17d97718)).
(If you really want, you can work on those too :))

You can find the current versions of documentation [here](https://nim-lang.github.io/Nim/lib.html), and most of the libraries (their `.nim` file)  are located in [lib/pure directory](https://github.com/nim-lang/Nim/tree/devel/lib/pure).

When you start working on one of these, write it in a comment below so there's no duplication of work.

Thank you in advance for your help!

**Comment by alehander42** [comment]
Is jsffi.nim with okayish doc, or is it in your todo list?

**Comment by narimiran** [comment]
> Is jsffi.nim with okayish doc, or is it in your todo list?

It is in the third, not mentioned category :) Not used very often (based on [this](https://gist.github.com/GULPF/dc97e5e745842138556d882c17d97718)).

But if you want to work on it — please do.

**Comment by alehander42** [comment]
this is a bit misleading, as it just means the JavaScript backend is not used so much in the github repos: however it is almost always imported in jsbackend-based code: I'll try to improve the docs

**Comment by narimiran** [comment]
> this is a bit misleading

It is hard to find some cover-it-all metric, so I decided to take that list as a starting point (rather than dumping a much longer list of modules :D). I'm aware of its limitations.

> however it is almost always imported in jsbackend-based code

I have no experience in JS, so if that's the case: `jsffi` is then quite high on our priority list.

> I'll try to improve the docs

Thank you!

**Comment by alehander42** [comment]
Sorry, I agree with the metric, just wanted to explain why it gives a strange result in this case, cheers

**Comment by dom96** [comment]
> see some before and after screenshots

This is great, I've got some feedback though regarding the existing docs:

* Many top-level examples are not testable, they use `echo` instead of `doAssert`. Please consider fixing this and enforcing it for any new documentation. Runnable examples are possible in top-level examples, right?

* The "Author" almost always is "Nim Contributors". When this is not the case the actual author is the person who created the module in the first place, but they may not have contributed to it in a while. I think it's far more genuine and in respect of our contributors to change everything to "Nim Contributors" with a link to the history of that file on GitHub (or some other page that shows the contributors).

**Comment by narimiran** [comment]
> Many top-level examples are not testable, they use `echo` instead of `doAssert`

...and they are part of `.. code-block::`, because I didn't like the looks of `runnableExamples` when used for top-level documentation (putting bold **Examples:** where that is not needed, some different-colored line to the left of the text following it).
That's why I decided to keep the existing `echo`s (since code-block is not tested), and continue to write the top-level examples in that style.

> The "Author" almost always is "Nim Contributors". When this is not the case the actual author is the person who created the module in the first place, but they may not have contributed to it in a while.

Can we just remove that field, since most of the existing documentation doesn't use it? (I introduced it because `sequtils` had it, but IMO it didn't reflect the reality.)


> please emphasise to people that the top-level examples should ideally be short and sweet

...while long enough to showcase a common usage of the module and its most-used functions. (I agree that JSON is a nice example)

**Comment by Araq** [comment]
> ...and they are part of .. code-block::, because I didn't like the looks of runnableExamples when used for top-level documentation (putting bold Examples: where that is not needed, some different-colored line to the left of the text following it).

We should change the styling instead. Examples that are not checked do bitrot.

**Comment by dom96** [comment]
> Can we just remove that field, since most of the existing documentation doesn't use it? (I introduced it because sequtils had it, but IMO it didn't reflect the reality, like you also noticed.)

Go for it.

**Comment by Jjp137** [comment]
I'm still learning Nim, but I like the language and I want to help. I'll work on improving the docs for `parseopt` since I have used it a little bit.

**Comment by jiro4989** [comment]
I'm learning nim too. I'll try to work docs of `parsecsv`.

**Comment by MandeepSinghey** [comment]
I am a new comer to NIM, happy to help. 

Actually as I am starting to use NIM that is one of the limitations i see for a newbee.

**Comment by narimiran** [comment]
@GordonBGood:
> I'm not sure where this would go on your list, but there are some modules that are very useful but don't appear on the main Nim Standard Library page listing the available modules.

Done. See https://nim-lang.github.io/Nim/lib.html for the updated version.

----

@MandeepSinghey:
> Explained the proc "pretty" in detail, file: json.nim with comments and sample program #10466

Before you start, take a look at the files for which @ThomasTJdev, @Jjp137 and @jiro4989 have written the improved documentation (thank you guys!!). There are links in the original post at the top, and that should help to get you started to see what and how to do. If you need any further help, feel free to contact me, either here or on IRC.

**Comment by Jjp137** [comment]
I'd like to help some more, so I'll work on improving the docs for the `random` module.

**Comment by Jjp137** [comment]
It's been a while, but now I'll work on improving the `logging` module's docs.

**Comment by jiro4989** [comment]
I will write `streams` module's documents.

**Comment by jiro4989** [comment]
I will write db_sqlite module's documents

**Comment by narimiran** [comment]
Version 0.20 is now released and all the improvements we did are now included in the [stable documentation](https://nim-lang.org/docs/lib.html).

I would take this opportunity to thank everybody who have helped with their contributions to improve Nim documentation. This is something that the whole community benefits from.

I'll close this now and any further improvements can be made on their own regardless of this thread.
