### ISSUE TITLE
Newruntime: Todo

### ISSUE THREAD

**Issue by Araq** [nim-lang/Nim#11217]
- [x] Ensure destructors are properly generated for closure environments.
- [x] Ensure that the destructor can be manually defined for recursive structures in order to prevent stack overflows or to implement more efficient iteration schemes.
- [x] Ensure closure iterators work with the new runtime.
- [x] Fix destructor injections for global variables. (Prevents ``koch temp`` from working.)
- [x] Document clearly what works and what doesn't.
- [x] The spec must reflect reality, ``=sink`` is here to stay.
