### ISSUE TITLE
Disabled tests for OpenBSD

### ISSUE THREAD

**Issue by euantorano** [nim-lang/Nim#14035]
This issue catalogues the tests that are disabled for the OpenBSD CI, with a future aim of removing as many of these disablements as possible:

- [x] `tests/coroutines/tgc.nim` - see #14032 for details
- [x] `tests/coroutines/twait.nim` - see #14032 for details
- [ ] `tests/dll/nimhcr_integration.nim` - see #12140 for details
- [ ] `tests/dll/nimhcr_unit.nim` - see #12140 for details
- [x] `tests/exception/t9657.nim` - see #13760 for details
- [x] `tests/niminaction/Chapter8/sfml/sfml_test.nim` - see #14033 for details
- [ ] `tests/parallel/tarray_of_channels.nim` - see #12142 for details
- [ ] `tests/stdlib/thttpclient_ssl.nim` - see #13773 for details
- [x] `tests/stdlib/tosprocterminate.nim` - see #13775 for details
- [ ] `tests/system/talloc2.nim` - see #14081 for details
- [ ] `tests/system/trealloc.nim`
- [x] `tests/async/tacceptcloserace/nim` - see #14031 for details
- [x] `tests/stdlib/tasynchttpserver.nim` - see #14036 for details
- [ ] `tests/parallel/tflowvar.nim` - see #14047 for details
- [x] `tests/stdlib/tgetaddrinfo` - see #12181 for details
- [ ] `tests/exception/t13115` - see #16167 for details; remove special case once nodejs updated >= 12.16.2

**Comment by timotheecour** [comment]
this meta-issue is very helpful; wish we could have same for other targets.

**Comment by euantorano** [comment]
I plan to add one for FreeBSD too, will probably do that today.

**Comment by lbartoletti** [comment]
> I plan to add one for FreeBSD too, will probably do that today.

Yes, please :)
Let me know if can I help you

**Comment by euantorano** [comment]
@lbartoletti FreeBSD issue live at #14075 - just running the test through to check the failure for `tests/dll/client.nim` to add a stand-alone issue for it.

**Comment by timotheecour** [comment]
@euantorano I added a openbsd:disabled test for https://github.com/nim-lang/Nim/pull/16167

tests/exception/t13115.nim

**Comment by euantorano** [comment]
Thanks @timotheecour, added to the list.

**Comment by timotheecour** [comment]
see also tests/js/tunittest_error.nim flaky test refs https://github.com/timotheecour/Nim/issues/648, slightly concerning

**Comment by VlkrS** [comment]
Propose to add tests/stdlib/tssl.nim (it's disabled and still failing for OpenBSD), and to re-evaluate tests/stdlib/thttpclient_ssl.nim (actually works at least for me)
