### ISSUE TITLE
Disabled tests for FreeBSD

### ISSUE THREAD

**Issue by euantorano** [nim-lang/Nim#14075]
This issue catalogues the tests that are disabled for the FreeBSD CI, with a future aim of removing as many of these disablements as possible:

- [x] `tests/dll/client.nim`
- [x] `tests/js/tconsole.nim` - see #12182 for details
- [x] `tests/niminaction/Chapter8/sfml/sfml_test.nim` - see #12141 for details
- [x] `tests/stdlib/tgetaddrinfo` - see #12181 for details
(EDIT)
- [ ] `tests/parallel/tblocking_channel.nim` #15725
- [ ] `tests/stdlib/tssl.nim` #15713

`rg disabled|grep 'freebsd\|openbsd'`
```
testament/tests/shouldfail/tvalgrind.nim:  # `disabled: "freebsd"` in the Testament configs above or else the tests will
tests/parallel/tblocking_channel.nim:disabled: "freebsd"
tests/stdlib/tssl.nim:  disabled: "freebsd"
tests/stdlib/tssl.nim:  disabled: "openbsd"
tests/stdlib/thttpclient_ssl.nim:  disabled: "openbsd"
tests/valgrind/tleak_arc.nim:disabled: "freebsd"
tests/valgrind/tleak_arc.nim:disabled: "openbsd"
tests/exception/t9657.nim:  disabled: "openbsd"
tests/dll/nimhcr_integration.nim:  disabled: "openbsd"
tests/dll/nimhcr_unit.nim:disabled: "openbsd"
tests/parallel/tflowvar.nim:  disabled: "openbsd"
tests/parallel/tarray_of_channels.nim:disabled: "openbsd"
tests/system/talloc2.nim:disabled: "openbsd"
tests/system/trealloc.nim:  disabled: "openbsd"
```

**Comment by euantorano** [comment]
Note: I've just ran the tests with `tests/dll/client.nim` enabled and `tests/js/console.nim` enabled, so these issues may already be fixed. PR incoming.

**Comment by euantorano** [comment]
I believe that all tests that can be enabled for FreeBSD are now enabled.

**Comment by timotheecour** [comment]
reopening refs https://github.com/nim-lang/Nim/pull/15726#issuecomment-716382763

**Comment by timotheecour** [comment]
rg disabled|grep 'freebsd\|openbsd'
```
testament/tests/shouldfail/tvalgrind.nim:  # `disabled: "freebsd"` in the Testament configs above or else the tests will
tests/parallel/tblocking_channel.nim:disabled: "freebsd"
tests/stdlib/tssl.nim:  disabled: "freebsd"
tests/stdlib/tssl.nim:  disabled: "openbsd"
tests/stdlib/thttpclient_ssl.nim:  disabled: "openbsd"
tests/valgrind/tleak_arc.nim:disabled: "freebsd"
tests/valgrind/tleak_arc.nim:disabled: "openbsd"
tests/exception/t9657.nim:  disabled: "openbsd"
tests/dll/nimhcr_integration.nim:  disabled: "openbsd"
tests/dll/nimhcr_unit.nim:disabled: "openbsd"
tests/parallel/tflowvar.nim:  disabled: "openbsd"
tests/parallel/tarray_of_channels.nim:disabled: "openbsd"
tests/system/talloc2.nim:disabled: "openbsd"
tests/system/trealloc.nim:  disabled: "openbsd"
```

**Comment by timotheecour** [comment]
~~regression: https://github.com/nim-lang/Nim/issues/18177~~ (oups, wrong issue)

**Comment by euantorano** [comment]
Note: #18177 is for OpenBSD, not FreeBSD.
