### ISSUE TITLE
Tracking of some ARC/ORC bugs

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#14224]
This issue is for some libraries which don't work with ARC and there's no short example. Also see https://github.com/Yardanico/random-stuff/issues/1
- [x] https://github.com/nitely/nim-regex compiler error in the C backend:
`./koch temp c --gc:arc nim-regex/src/regex.nim`
```
/home/dian/.nim/compiler/nim.nim(104) nim
/home/dian/.nim/compiler/nim.nim(81) handleCmdLine
/home/dian/.nim/compiler/cmdlinehelper.nim(91) loadConfigsAndRunMainCommand
/home/dian/.nim/compiler/main.nim(196) mainCommand
/home/dian/.nim/compiler/main.nim(98) commandCompileToC
/home/dian/.nim/compiler/modules.nim(143) compileProject
/home/dian/.nim/compiler/modules.nim(84) compileModule
/home/dian/.nim/compiler/passes.nim(210) processModule
/home/dian/.nim/compiler/passes.nim(86) processTopLevelStmt
/home/dian/.nim/compiler/cgen.nim(1917) myProcess
/home/dian/.nim/compiler/cgen.nim(968) genProcBody
/home/dian/.nim/compiler/ccgstmts.nim(1561) genStmts
/home/dian/.nim/compiler/ccgexprs.nim(2665) expr
/home/dian/.nim/compiler/ccgexprs.nim(2451) genStmtList
/home/dian/.nim/compiler/ccgstmts.nim(1561) genStmts
/home/dian/.nim/compiler/ccgexprs.nim(2712) expr
/home/dian/.nim/compiler/ccgstmts.nim(1211) genTryGoto
/home/dian/.nim/compiler/ccgexprs.nim(2665) expr
/home/dian/.nim/compiler/ccgexprs.nim(2451) genStmtList
/home/dian/.nim/compiler/ccgstmts.nim(1561) genStmts
/home/dian/.nim/compiler/ccgexprs.nim(2665) expr
/home/dian/.nim/compiler/ccgexprs.nim(2451) genStmtList
/home/dian/.nim/compiler/ccgstmts.nim(1561) genStmts
/home/dian/.nim/compiler/ccgexprs.nim(2629) expr
/home/dian/.nim/compiler/ccgcalls.nim(627) genCall
/home/dian/.nim/compiler/ccgcalls.nim(250) genPrefixCall
/home/dian/.nim/compiler/cgen.nim(596) initLocExpr
/home/dian/.nim/compiler/ccgexprs.nim(2679) expr
/home/dian/.nim/compiler/cgen.nim(1215) genProc
/home/dian/.nim/compiler/cgen.nim(1158) genProcNoForward
/home/dian/.nim/compiler/cgen.nim(1024) genProcAux
/home/dian/.nim/compiler/cgen.nim(968) genProcBody
/home/dian/.nim/compiler/ccgstmts.nim(1561) genStmts
/home/dian/.nim/compiler/ccgexprs.nim(2665) expr
/home/dian/.nim/compiler/ccgexprs.nim(2451) genStmtList
/home/dian/.nim/compiler/ccgstmts.nim(1561) genStmts
/home/dian/.nim/compiler/ccgexprs.nim(2712) expr
/home/dian/.nim/compiler/ccgstmts.nim(1272) genTryGoto
/home/dian/.nim/compiler/ccgstmts.nim(1561) genStmts
/home/dian/.nim/compiler/ccgexprs.nim(2665) expr
/home/dian/.nim/compiler/ccgexprs.nim(2440) genStmtList
/home/dian/.nim/compiler/cccgstmts.nim(1561) genStmts
/home/dian/.nim/compiler/ccgexprs.nim(2629) expr
/home/dian/.nim/compiler/ccgcalls.nim(627) genCall
/home/dian/.nim/compiler/ccgcalls.nim(250) genPrefixCall
/home/dian/.nim/compiler/cgen.nim(596) initLocExpr
/home/dian/.nim/compiler/ccgexprs.nim(2561) expr
/home/dian/.nim/compiler/cgen.nim(1215) genProc
/home/dian/.nim/compiler/cgen.nim(1158) genProcNoForward
/home/dian/.nim/compiler/cgen.nim(1024) genProcAux
/home/dian/.nim/compiler/cgen.nim(968) genProcBody
/home/dian/.nim/compiler/ccgstmts.nim(1561) genStmts
/home/dian/.nim/compiler/ccgexprs.nim(2665) expr
/home/dian/.nim/compiler/ccgexprs.nim(2440) genStmtList
/home/dian/.nim/compiler/ccgstmts.nim(1561) genStmts
/home/dian/.nim/compiler/ccgexprs.nim(2629) expr
/home/dian/.nim/compiler/ccgcalls.nim(627) genCall
/home/dian/.nim/compiler/ccgcalls.nim(237) genPrefixCall
/home/dian/.nim/compiler/ccgcalls.nim(220) genArg
/home/dian/.nim/compiler/cgen.nim(609) initLocExprSingleUse
/home/dian/.nim/compiler/ccgexprs.nim(2658) expr
/home/dian/.nim/compiler/ccgexprs.nim(743) genAddr
/home/dian/.nim/compiler/cgen.nim(596) initLocExpr
/home/dian/.nim/compiler/ccgexprs.nim(2661) expr
/home/dian/.nim/compiler/ccgexprs.nim(799) genRecordField
/home/dian/.nim/compiler/ccgexprs.nim(777) lookupFieldAgain
/home/dian/.nim/lib/system/assertions.nim(29) failedAssertImpl
/home/dian/.nim/lib/system/assertions.nim(22) raiseAssert
/home/dian/.nim/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: /home/dian/.nim/compiler/ccgexprs.nim(777, 11) `ty.kind in {tyTuple, tyObject}`  [AssertionDefect]
FAILURE
```

Update: managed to reproduce it - https://github.com/nim-lang/Nim/issues/14236

Also see https://github.com/nim-lang/Nim/wiki/Status-of-gc:arc-and-gc:orc-(library-compatibility)

**Comment by ghost** [comment]
- [ ] https://github.com/unicredit/cello has a test where it relies on the fact that strings are shared, extracted test case from https://github.com/unicredit/cello/blob/master/tests/rotated_string.nim#L39, not sure if this can be considered a bug.
```nim

type RotatedString* = object
  underlying: string
  shift: int

proc rotate*(s: string, i: int): RotatedString =
  result = RotatedString(underlying: s, shift: i)

proc rotate*(s: var string, i: int): RotatedString =
  result = RotatedString(shift: i)
  shallowCopy(result.underlying, s)

proc `[]`*(r: RotatedString, i: int): char {.inline.} =
  let L = r.underlying.len
  assert 0 <= i and i < L
  let s = i + r.shift
  if s < L:
    return r.underlying[s]
  else:
    return r.underlying[s - L]

proc `[]=`*(r: var RotatedString, i: int, c: char) {.inline.} =
  let L = r.underlying.len
  assert 0 <= i and i < L
  let s = i + r.shift
  if s < L:
    r.underlying[s] = c
  else:
    r.underlying[s - L] = c

proc `$`*(r: RotatedString): string =
  r.underlying[r.shift .. r.underlying.high] & r.underlying[0 ..< r.shift]

var
  x = "Hello, world"
  y = x.rotate(5)

y[0] = 'f'
assert x[5] == 'f'
```

**Comment by kaushalmodi** [comment]
- [x] https://github.com/citycide/glob

### Steps to reproduce the issue

1. `nimble install glob`
2. Create this `t.nim`:
    ```nim
    import glob
    for path in walkGlob("src"):
      echo path
    ```
3. Run `nim c --gc:arc t.nim`

### Error

```
/home/kmodi/.nimble/pkgs/glob-0.9.0/glob.nim(507, 32) Hint: passing 'matchPattern' to a sink parameter introduces an implicit copy; use 'move(matchPattern)' to prevent it [Performance]
fatal.nim(49)            sysFatal
Error: unhandled exception: ccgexprs.nim(777, 11) `ty.kind in {tyTuple, tyObject}`  [AssertionDefect]
```

**Comment by andreaferretti** [comment]
Neo has a [suite](https://github.com/unicredit/neo/blob/master/tests/dense/dtrivial_ops.nim#L82-L118) checking that some simple operations do not copy data, but rather share storage with the original matrix - for instance, taking a transpose. This fails with `gc: arc`. Moreover, changing - say - the definition of the transpose from

```nim
proc t*[A](m: Matrix[A]): Matrix[A] =
  if m.isFull:
    matrix(
      order = (if m.order == rowMajor: colMajor else: rowMajor),
      M = m.N,
      N = m.M,
      data = m.data
    )
  else:
    m.clone().t
```

to

```nim
proc t*[A](m: Matrix[A]): Matrix[A] =
  if m.isFull:
    result = matrix(
      order = (if m.order == rowMajor: colMajor else: rowMajor),
      M = m.N,
      N = m.M,
      data = @[]
    )
    shallowCopy(result.data, m.data)
  else:
    m.clone().t
```

i.e., using `shallowCopy` explicitly, results in

```
Error: unhandled exception: liftdestructors.nim(465, 14) `t.destructor != nil`  [AssertionDefect]
```

**Comment by andreaferretti** [comment]
[Emmy](https://github.com/unicredit/emmy) has a similar failure about sharing storage, **but** also a failure in [some tests](https://github.com/unicredit/emmy/blob/master/tests/tintegers_modulo.nim#L48-L87) that apparently [do not have anything to do](https://github.com/unicredit/emmy/blob/master/emmy/integers_modulo.nim) with sharing storage.

**Comment by andreaferretti** [comment]
[Rosencrantz](https://github.com/andreaferretti/rosencrantz) just fails to compile with

```
/Users/andrea/esperimenti/rosencrantz/rosencrantz/headersupport.nim(31, 26) Error: undeclared identifier: 'await'
```

**Comment by cooldome** [comment]
@Yardanico. Could you please continue testing Nim packages latest Nim dev, I think we have fixed a number of issues in the last week.

**Comment by ghost** [comment]
@cooldome yeah, I'll do that :)

**Comment by ghost** [comment]
An update on latest optimizer + cursorifier - right now I found that `nim-markdown` and `RBTreeNim` trigger some kind of Nim cursorifier bug which makes them crash (in tests).

`nimly` - some other ARC bug, not caused by the cursorifier.

Also `NiGui` example_04_msgboxes.nim crashes with ARC when clicking on a button and then clicking "ok" in the messagebox.

Any help in minimizing these so they're easy to reproduce would be very welcome :)

Quite a lot of stuff works though - including bigger projects like https://github.com/fox0430/moe

**Comment by ghost** [comment]
Seems like nimly works with ORC on latest devel now, same for markdown, rbtreenim, moe.

NiGui issue is still there.

**Comment by ghost** [comment]
Did some testing of nimforum with ORC both single-threaded/multi-threaded.

- In single-threaded mode nimforum with ORC seems to leak ~3mb per 95k requests.

- In multi-threaded mode nimforum with ORC is ~3.5x SLOWER than single-threaded, and leaks orders of magnitude more (~800MB RAM for 26k requests) - with other GCes like refc or markAndSweep multi-threaded performance is of course much better than single-threaded.

It really seems to me that httpbeast and ORC don't like each other at all

**Comment by ghost** [comment]
Also with multi-threaded mode ARC and ORC behave roughly the same - leak the same amount of memory (800-900MB RAM), and are slower than single-threaded.

**Comment by ghost** [comment]
Tested httpbeast directly - both ARC/ORC don't leak any memory with the hello world example of it, but ARC/ORC is 3x slower in multi-threaded helloworld example

**Comment by Araq** [comment]
Test for a better example, helloworld is meaningless.

**Comment by ghost** [comment]
Sorry, I didn't make a better httpbeast example yet, but found an ORC crash in https://github.com/kostya/benchmarks/blob/master/havlak/havlak.nim again (it worked before, but stopped working relatively recently); I'll try to minimize and git bisect to find the commit when that behaviour started showing up.

**Comment by ghost** [comment]
The first bad commit seems to be d19316bbb986a7dd1d6d091173963f6e74c65991, not minimised test case is https://gist.github.com/Yardanico/1ad44c09a70e2d781b84f147cd049134

**Comment by ghost** [comment]
It seems to run fine if I replace `while j.traceStack.len > until:` with old `while j.traceStack.len > 0:`  like it was before in https://github.com/nim-lang/Nim/blob/devel/lib/system/orc.nim#L138

**Comment by ghost** [comment]
I feel like this issue is no longer needed, if there are any specific ARC/ORC bugs it's better to have separate issues for them.
