### ISSUE TITLE
[meta] failed asserts in int128.nim

### ISSUE THREAD

**Issue by narimiran** [nim-lang/Nim#14989]
This is a meta-issue, which tries to collect all the issues that are open because some `assert` in `int128.nim` has failed. The idea is to have all of them in once place, because one fix might potentially close multiple issues.

1. ``int128.nim(68, 11) `arg.sdata(3) == -1` out of range [AssertionDefect]``

    * ---> for both issues, the value of `args.sdata(3)` is `low(int32)` (`-2147483648`)
    - [ ] https://github.com/nim-lang/Nim/issues/8868
    - [ ] https://github.com/nim-lang/Nim/issues/9326

1. ``int128.nim(71, 11) `arg.sdata(3) == 0` out of range [AssertionDefect]``

    - [x] https://github.com/nim-lang/Nim/issues/12684

1. ``int128.nim(72, 11) `arg.sdata(2) == 0` out of range [AssertionDefect]``

    * ---> for all issues, the value of `args.sdata(2)` is `1`
    - [x] https://github.com/nim-lang/Nim/issues/6834
    - [ ] https://github.com/nim-lang/Nim/issues/8141
    - [ ] https://github.com/nim-lang/Nim/issues/12938
    - [ ] https://github.com/nim-lang/Nim/issues/14193
    - [ ] https://github.com/nim-lang/Nim/issues/17974

1. ``int128.nim(330, 11) `false` overflow [AssertionDefect]``

    - [x] https://github.com/nim-lang/Nim/issues/12636
    - [x] https://github.com/nim-lang/Nim/issues/12897

First three points (lines 68, 71, 72) are part of `proc toInt64*(arg: Int128): int64`.
The last point (line 330) is part of ``proc `*`(a: Int128, b: uint32): Int128``.

**Comment by krux02** [comment]
I looked into this because I thought there would be a bug in int128. But these are all overflow and out of range error messages. The error messages could be improved for sure, but here is no bug in int128.
