### ISSUE TITLE
[runnableExamples] miscellaneous issues

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8695]
## major
- [ ] Some runnable examples are not executed. #7280
- [ ] runnableExamples doesn't work at module level #8641
- [ ] proposal: a runnableExamples below a proc becomes part of that symbol doc; would fix #7280 and result in easier to read code #8536
- [ ] `Error: undeclared identifier: '|'` when using `|` inside a `runnableExamples:` #8694

## minor
- [ ] X_examples.nim generated by runnableExamples should show line number where they came from #8289

## links
```
./compiler/semexprs.nim
 keep the imports in runnableExamples visible in generated html doc (#8354)
```

**Comment by dom96** [comment]
What's the purpose of this issue? Just a list of other issues? Why?

**Comment by timotheecour** [comment]
in short, it helps organize:
* they're all related and I find it very helpful when I'm working on a PR for fixing 1 issue to see other related issues
* it helps track progress towards fixing a category of bugs; harder to tell the big picture without this meta-issue
* sometimes it's more convenient to just add a bug to this list without creating a separate issue
